# Generated by Django 2.0.7 on 2020-02-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=None, max_length=15)),
                ('name', models.CharField(blank=True, default=None, max_length=255)),
                ('initials', models.CharField(blank=True, default=None, max_length=31)),
                ('fund_type', models.CharField(blank=True, default=None, max_length=31)),
                ('establishment_date', models.DateField(default=None, null=True)),
                ('modified_date', models.DateField(default=None, null=True)),
                ('unit_net_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('accumulative_net_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('daily_increase_date', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('recent_1_week', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('recent_1_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('recent_3_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('recent_6_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('recent_1_year', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('recent_2_year', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('recent_3_year', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('this_year', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('since_inception', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
            ],
            options={
                'db_table': 'funds',
            },
        ),
        migrations.CreateModel(
            name='FundHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=None, null=True)),
                ('unit_net_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('accumulative_net_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('daily_increase_date', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fund', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_data', to='east_money.Fund')),
            ],
            options={
                'db_table': 'fund_history',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255)),
                ('code', models.CharField(blank=True, default=None, max_length=15)),
                ('modified_date', models.DateField(default=None, null=True)),
                ('daily_increase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
        migrations.AddField(
            model_name='fund',
            name='stocks',
            field=models.ManyToManyField(db_constraint=False, related_name='funds', to='east_money.Stock'),
        ),
    ]
