# Generated by Django 2.0.7 on 2020-03-05 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('east_money', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='daily_increase_date',
            new_name='daily_increase_rate',
        ),
        migrations.RenameField(
            model_name='fundhistory',
            old_name='daily_increase_date',
            new_name='daily_increase_rate',
        ),
    ]
