# Generated by Django 2.0.7 on 2020-02-28 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('east_money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, default=None, max_length=15)),
                ('modified_date', models.DateField(default=None, null=True)),
                ('daily_increase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'favors',
            },
        ),
        migrations.AlterUniqueTogether(
            name='favor',
            unique_together={('content_type', 'object_id', 'code')},
        ),
    ]
