# Generated by Django 2.0.7 on 2020-02-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('east_money', '0002_auto_20200228_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=15, unique=True),
        ),
    ]
